name: LINUX-CI

on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/ci.yml'
      - './Makefile'
      - 'gpio'
  pull_request:
    branches: [ "**" ]
    paths:
      - '.github/workflows/ci.yml'
      - './Makefile'
      - 'gpio'
  workflow_dispatch:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Install prerequisites
      run:  make install-requirements
    - name: build code
      run:  make all
    - name: test code
      run:  make test
      
